blank_issues_enabled: false
contact_links:
  - name: Questions or Support
    url: https://github.com/larpios/riffl/discussions
    about: Please ask questions and seek support in our discussions forum.
