use crate::audio::channel_strip::ChannelStrip;
use crate::audio::effect_processor::TransportCommand;
use crate::audio::pending_note::PendingNote;
use crate::audio::voice::{Voice, VoiceLfoState};
use crate::pattern::note::NoteEvent;
use crate::pattern::pattern::Pattern;
use crate::pattern::EffectType;

impl super::Mixer {
    /// Process a pattern row, triggering or stopping samples based on note events.
    ///
    /// For each channel in the row:
    /// - `NoteEvent::On(note)`: Start playing the sample at the instrument index,
    ///   pitched to match the note's frequency, with velocity-based volume.
    /// - `NoteEvent::Off`: Stop the voice on that channel.
    /// - `NoteEvent::Cut`: Immediately hard-silence the voice (no envelope release).
    /// - No event: The existing voice continues playing.
    ///
    /// Returns any transport commands generated by effects (BPM changes,
    /// position jumps, pattern breaks).
    pub fn tick(&mut self, row_index: usize, pattern: &Pattern) -> Vec<TransportCommand> {
        // Sync track mixing state (volume, pan, mute/solo)
        self.update_tracks(pattern.tracks());

        let row = match pattern.get_row(row_index) {
            Some(r) => r,
            None => return Vec::new(),
        };

        // Clear pending notes from previous row
        self.pending_notes.clear();
        self.effect_processor.reset_row_slides();

        let mut transport_commands = Vec::new();

        for (ch, cell) in row.iter().enumerate() {
            if ch >= self.voices.len() {
                break;
            }

            // Skip muted/non-soloed channels: don't trigger new notes
            let audible = !self
                .channel_strips
                .get(ch)
                .is_some_and(ChannelStrip::is_silent);

            // In classical trackers, specifying an instrument number OR triggering a new
            // note resets the channel volume, clearing any previous volume slides or overrides.
            if cell.instrument.is_some() || matches!(&cell.note, Some(NoteEvent::On(_))) {
                if let Some(state) = self.effect_processor.channel_state_mut(ch) {
                    state.volume_override = None;
                }
            }

            // Determine the note frequency for effect processing
            let note_frequency = match &cell.note {
                Some(NoteEvent::On(note)) => Some(note.frequency()),
                _ => None,
            };

            // Process effects for this channel
            let cmds = self
                .effect_processor
                .process_row(ch, &cell.effects, note_frequency);

            if let Some(vol) = cell.volume {
                if let Some(state) = self.effect_processor.channel_state_mut(ch) {
                    state.volume_override = Some((vol as f32 / 64.0).clamp(0.0, 2.0));
                }
            }

            for cmd in &cmds {
                if let TransportCommand::SetTpl(tpl) = cmd {
                    self.set_tpl(*tpl);
                }
            }

            transport_commands.extend(cmds);

            // Apply effect-based panning (8xx/panbrello) to the channel strip.
            // Only effect panning updates the strip; instrument panning is applied at render time.
            // Panning is stored as 0.0 (left) → 1.0 (right); strip uses -1.0 → 1.0.
            if let Some(pan_01) = self.effect_processor.channel_effect_panning(ch) {
                let pan = pan_01 * 2.0 - 1.0;
                if let Some(strip) = self.channel_strips.get_mut(ch) {
                    strip.set_effect_pan_immediate(pan);
                }
            }

            match &cell.note {
                Some(NoteEvent::On(note)) => {
                    if !audible {
                        // Muted channel: stop any playing voice, don't start new one
                        self.voices[ch] = None;
                        continue;
                    }

                    let has_tone_porta = cell.effects.iter().any(|e| {
                        matches!(
                            e.effect_type(),
                            Some(EffectType::PortamentoToNote)
                                | Some(EffectType::TonePortamentoVolumeSlide)
                                | Some(EffectType::PortamentoFine)
                                | Some(EffectType::PortamentoExtraFine)
                        )
                    });

                    let note_frequency = note.frequency();
                    let instrument_idx = cell.instrument.unwrap_or(note.instrument) as usize;

                    // Resolve sample index: use keyzone matching if instrument has keyzones,
                    // otherwise fall back to instrument's sample_index.
                    let resolved_sample_idx =
                        if let Some(inst) = self.instruments.get(instrument_idx) {
                            inst.resolve_sample_index(note.midi_note(), note.velocity)
                        } else {
                            Some(instrument_idx)
                        };

                    if let Some(resolved_sample_idx) = resolved_sample_idx {
                        if resolved_sample_idx < self.samples.len() {
                            let sample = &self.samples[resolved_sample_idx];
                            // Calculate playback rate to pitch the sample to the desired note.
                            // The sample's base_note (default C-4) plays at original speed.
                            // Higher notes play faster, lower notes play slower.
                            let base_freq = sample.base_frequency();
                            let target_freq = note_frequency;
                            let sample_rate_ratio =
                                sample.sample_rate() as f64 / self.output_sample_rate as f64;

                            let mut hz_to_rate = (1.0 / base_freq) * sample_rate_ratio;

                            // Apply sample-level finetune (in cents)
                            if sample.finetune != 0 {
                                hz_to_rate *= 2.0_f64.powf(sample.finetune as f64 / 1200.0);
                            }

                            // Apply finetune from instrument or effect override
                            let finetune = if let Some(ft_override) =
                                self.effect_processor.finetune_override(ch)
                            {
                                ft_override
                            } else {
                                self.instruments
                                    .get(instrument_idx)
                                    .map(|inst| inst.finetune)
                                    .unwrap_or(0)
                            };

                            if finetune != 0 {
                                // ProTracker finetune formula: 1 unit = 1/8th of a semitone
                                hz_to_rate *= 2.0_f64.powf(finetune as f64 / (12.0 * 8.0));
                            }

                            let playback_rate = target_freq * hz_to_rate;

                            let is_amiga = self
                                .effect_processor
                                .channel_state(ch)
                                .map(|s| {
                                    s.slide_mode == crate::audio::pitch::SlideMode::AmigaPeriod
                                })
                                .unwrap_or(false);

                            let clock = if self.format_is_s3m {
                                crate::audio::pitch::AMIGA_S3M_CLOCK
                            } else {
                                crate::audio::pitch::AMIGA_PAL_CLOCK
                            };

                            let period_clock = if is_amiga {
                                clock * base_freq / sample.sample_rate() as f64
                            } else {
                                clock
                            };

                            if is_amiga {
                                self.effect_processor.set_period_clock(ch, period_clock);
                            }

                            let inst_vol = self
                                .instruments
                                .get(instrument_idx)
                                .map(|inst| inst.volume)
                                .unwrap_or(1.0);
                            let velocity = note.velocity as f32;
                            let velocity_gain = (velocity / 127.0) * inst_vol * sample.volume;

                            // Apply instrument panning to instrument_pan_override.
                            // If the instrument has no default panning, clear it so the
                            // channel's base pan (strip or 8xx effect) is used instead.
                            if let Some(state) = self.effect_processor.channel_state_mut(ch) {
                                state.instrument_pan_override = self
                                    .instruments
                                    .get(instrument_idx)
                                    .and_then(|i| i.panning)
                                    .map(|p| (p + 1.0) / 2.0);
                            }

                            if has_tone_porta && self.voices[ch].is_some() {
                                // A tone portamento effect exists and a voice is already playing.
                                // Do not trigger a new sample. The TrackerEffectProcessor handles target pitch updates.
                                // However, we update the voice's instrument settings (volume, panning, etc) if an instrument is specified.
                                if let Some(voice) = &mut self.voices[ch] {
                                    // Reset key_on and fadeout state for the new note
                                    voice.key_on = true;
                                    voice.fadeout_multiplier = 1.0;
                                    voice.last_fadeout_tick = 0;

                                    if cell.instrument.is_some() {
                                        voice.instrument_index = instrument_idx;
                                        voice.velocity_gain = velocity_gain;
                                        voice.hz_to_rate = hz_to_rate;

                                        // Update playback rate to match current sliding frequency with new hz_to_rate
                                        if let Some(current_freq) =
                                            self.effect_processor.effective_frequency(ch)
                                        {
                                            voice.playback_rate = current_freq * hz_to_rate;
                                        }

                                        // Update LFO state for new instrument, but do NOT reset
                                        // envelopes — portamento continues the playing note.
                                        voice.lfo = VoiceLfoState::new(
                                            self.instruments.get(instrument_idx),
                                        );
                                    }
                                }
                            } else {
                                // Check for Note Delay (EDx)
                                if let Some(delay_tick) = self
                                    .effect_processor
                                    .channel_state(ch)
                                    .and_then(|s| s.note_delay_tick)
                                {
                                    let frames_per_row = self
                                        .effect_processor
                                        .channel_state(ch)
                                        .map(|s| s.frames_per_row)
                                        .unwrap_or(6000);
                                    let frames_per_tick = frames_per_row / self.tpl;
                                    let trigger_frame = delay_tick as u32 * frames_per_tick;

                                    let offset = self.effect_processor.sample_offset(ch);

                                    self.pending_notes.push(PendingNote {
                                        channel: ch,
                                        instrument_index: instrument_idx,
                                        sample_index: resolved_sample_idx,
                                        playback_rate,
                                        velocity_gain,
                                        hz_to_rate,
                                        triggered_note_freq: target_freq,
                                        period_clock,
                                        offset,
                                        trigger_frame,
                                    });
                                } else {
                                    let mut voice = Voice::new(
                                        self.instruments.get(instrument_idx),
                                        instrument_idx,
                                        resolved_sample_idx,
                                        playback_rate,
                                        velocity_gain,
                                        hz_to_rate,
                                        target_freq,
                                    );
                                    if let Some(offset) = self.effect_processor.sample_offset(ch) {
                                        voice = voice.with_position(offset as f64);
                                    }

                                    self.voices[ch] = Some(voice);
                                }
                            }
                        }
                    }
                }
                Some(NoteEvent::Off) => {
                    if let Some(voice) = &mut self.voices[ch] {
                        let has_envelope = self
                            .instruments
                            .get(voice.instrument_index)
                            .is_some_and(|inst| {
                                inst.volume_adsr.is_some()
                                    || inst.volume_envelope.as_ref().is_some_and(|env| env.enabled)
                            });

                        let has_sustain_loop =
                            self.samples.get(voice.sample_index).is_some_and(|s| {
                                s.sustain_loop_mode != crate::audio::sample::LoopMode::NoLoop
                                    && s.sustain_loop_end > s.sustain_loop_start
                            });

                        if has_envelope || has_sustain_loop {
                            // Release the key: envelope continues past sustain,
                            // and sustain loop releases so the sample plays through.
                            voice.key_on = false;
                        } else {
                            self.voices[ch] = None;
                        }
                    }
                }
                Some(NoteEvent::Cut) => {
                    // Hard-silence: kill voice immediately with no envelope release.
                    self.voices[ch] = None;
                    if let Some(s) = self.effect_processor.channel_state_mut(ch) {
                        s.reset();
                    }
                }
                None => {
                    // No note event — check if an instrument was provided with a tone portamento.
                    // This handles cases like `305 .. .. 04` where instrument 4 is set without a new note.
                    if let Some(instrument_idx) = cell.instrument {
                        let instrument_idx = instrument_idx as usize;
                        let has_tone_porta = cell.effects.iter().any(|e| {
                            matches!(
                                e.effect_type(),
                                Some(EffectType::PortamentoToNote)
                                    | Some(EffectType::TonePortamentoVolumeSlide)
                                    | Some(EffectType::PortamentoFine)
                                    | Some(EffectType::PortamentoExtraFine)
                            )
                        });

                        if has_tone_porta && self.voices[ch].is_some() {
                            let last_freq = self.effect_processor.last_note_frequency(ch);

                            // Resolve sample for the current instrument at the last frequency.
                            let midi_note =
                                (12.0f64 * (last_freq / 440.0f64).log2() + 69.0f64).round() as u8;
                            let resolved_sample_idx = if let Some(inst) =
                                self.instruments.get(instrument_idx)
                            {
                                if inst.keyzones.is_empty() {
                                    Some(instrument_idx)
                                } else {
                                    inst.resolve_sample_index(midi_note, 100) // Default velocity
                                }
                            } else {
                                Some(instrument_idx)
                            };

                            if let Some(resolved_sample_idx) = resolved_sample_idx {
                                if resolved_sample_idx < self.samples.len() {
                                    let sample = &self.samples[resolved_sample_idx];
                                    let base_freq = sample.base_frequency();
                                    let sample_rate_ratio = sample.sample_rate() as f64
                                        / self.output_sample_rate as f64;

                                    let mut hz_to_rate = (1.0 / base_freq) * sample_rate_ratio;
                                    if sample.finetune != 0 {
                                        hz_to_rate *= 2.0_f64.powf(sample.finetune as f64 / 1200.0);
                                    }

                                    let finetune = if let Some(ft_override) =
                                        self.effect_processor.finetune_override(ch)
                                    {
                                        ft_override
                                    } else {
                                        self.instruments
                                            .get(instrument_idx)
                                            .map(|inst| inst.finetune)
                                            .unwrap_or(0)
                                    };

                                    if finetune != 0 {
                                        hz_to_rate *= 2.0_f64.powf(finetune as f64 / (12.0 * 8.0));
                                    }

                                    let inst_vol = self
                                        .instruments
                                        .get(instrument_idx)
                                        .map(|inst| inst.volume)
                                        .unwrap_or(1.0);
                                    let velocity_gain = (100.0 / 127.0) * inst_vol * sample.volume;

                                    // Apply instrument panning to instrument_pan_override.
                                    if let Some(state) = self.effect_processor.channel_state_mut(ch)
                                    {
                                        state.instrument_pan_override = self
                                            .instruments
                                            .get(instrument_idx)
                                            .and_then(|i| i.panning)
                                            .map(|p| (p + 1.0) / 2.0);
                                    }

                                    if let Some(voice) = &mut self.voices[ch] {
                                        voice.instrument_index = instrument_idx;
                                        voice.sample_index = resolved_sample_idx;
                                        voice.velocity_gain = velocity_gain;
                                        voice.hz_to_rate = hz_to_rate;

                                        // Update playback rate to match current sliding frequency with new hz_to_rate
                                        if let Some(current_freq) =
                                            self.effect_processor.effective_frequency(ch)
                                        {
                                            voice.playback_rate = current_freq * hz_to_rate;
                                        }

                                        // Reset key_on and fadeout state for the new instrument trigger
                                        voice.key_on = true;
                                        voice.fadeout_multiplier = 1.0;

                                        // Update LFO state for new instrument, but do NOT reset
                                        // envelopes — portamento continues the playing note.
                                        voice.lfo = VoiceLfoState::new(
                                            self.instruments.get(instrument_idx),
                                        );
                                    }

                                    // Update period clock for the channel if in Amiga mode
                                    let is_amiga = self
                                        .effect_processor
                                        .channel_state(ch)
                                        .map(|s| {
                                            s.slide_mode
                                                == crate::audio::pitch::SlideMode::AmigaPeriod
                                        })
                                        .unwrap_or(false);
                                    if is_amiga {
                                        let clock = if self.format_is_s3m {
                                            crate::audio::pitch::AMIGA_S3M_CLOCK
                                        } else {
                                            crate::audio::pitch::AMIGA_PAL_CLOCK
                                        };
                                        let period_clock =
                                            clock * base_freq / sample.sample_rate() as f64;
                                        self.effect_processor.set_period_clock(ch, period_clock);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        transport_commands
    }
}
